/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\Android\\Github\\storemanager\\homeweb\\node_modules\\@vuepress\\core\\lib\\app\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-6dd8c284",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("HomeLayout", "v-6dd8c284").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-2b910858",
    path: "/game/all/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2b910858").then(next)
    },
  },
  {
    path: "/game/all/index.html",
    redirect: "/game/all/"
  },
  {
    name: "v-f094d918",
    path: "/game/chesscard/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f094d918").then(next)
    },
  },
  {
    path: "/game/chesscard/index.html",
    redirect: "/game/chesscard/"
  },
  {
    name: "v-16017424",
    path: "/game/risk/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-16017424").then(next)
    },
  },
  {
    path: "/game/risk/index.html",
    redirect: "/game/risk/"
  },
  {
    name: "v-15069ed8",
    path: "/game/shoot/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-15069ed8").then(next)
    },
  },
  {
    path: "/game/shoot/index.html",
    redirect: "/game/shoot/"
  },
  {
    name: "v-8f482b58",
    path: "/game/smart/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8f482b58").then(next)
    },
  },
  {
    path: "/game/smart/index.html",
    redirect: "/game/smart/"
  },
  {
    name: "v-81c7d824",
    path: "/game/synthesize/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-81c7d824").then(next)
    },
  },
  {
    path: "/game/synthesize/index.html",
    redirect: "/game/synthesize/"
  },
  {
    name: "v-81780c32",
    path: "/github/android/all/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-81780c32").then(next)
    },
  },
  {
    path: "/github/android/all/index.html",
    redirect: "/github/android/all/"
  },
  {
    name: "v-c5bfcbf2",
    path: "/github/android/animation/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c5bfcbf2").then(next)
    },
  },
  {
    path: "/github/android/animation/index.html",
    redirect: "/github/android/animation/"
  },
  {
    name: "v-69247671",
    path: "/github/android/architecture/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-69247671").then(next)
    },
  },
  {
    path: "/github/android/architecture/index.html",
    redirect: "/github/android/architecture/"
  },
  {
    name: "v-ac727eb2",
    path: "/github/android/component/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ac727eb2").then(next)
    },
  },
  {
    path: "/github/android/component/index.html",
    redirect: "/github/android/component/"
  },
  {
    name: "v-2ab17667",
    path: "/github/android/project/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2ab17667").then(next)
    },
  },
  {
    path: "/github/android/project/index.html",
    redirect: "/github/android/project/"
  },
  {
    name: "v-4f7fc17a",
    path: "/github/android/synthesize/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4f7fc17a").then(next)
    },
  },
  {
    path: "/github/android/synthesize/index.html",
    redirect: "/github/android/synthesize/"
  },
  {
    name: "v-1aa30e66",
    path: "/github/android/view/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1aa30e66").then(next)
    },
  },
  {
    path: "/github/android/view/index.html",
    redirect: "/github/android/view/"
  },
  {
    name: "v-72675a72",
    path: "/github/flutter/all/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-72675a72").then(next)
    },
  },
  {
    path: "/github/flutter/all/index.html",
    redirect: "/github/flutter/all/"
  },
  {
    name: "v-37aaa0c7",
    path: "/github/flutter/project/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-37aaa0c7").then(next)
    },
  },
  {
    path: "/github/flutter/project/index.html",
    redirect: "/github/flutter/project/"
  },
  {
    name: "v-33e83461",
    path: "/github/h5/h5/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-33e83461").then(next)
    },
  },
  {
    path: "/github/h5/h5/index.html",
    redirect: "/github/h5/h5/"
  },
  {
    name: "v-2c855a5a",
    path: "/github/h5/all/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2c855a5a").then(next)
    },
  },
  {
    path: "/github/h5/all/index.html",
    redirect: "/github/h5/all/"
  },
  {
    name: "v-ed11587e",
    path: "/github/h5/hexo/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ed11587e").then(next)
    },
  },
  {
    path: "/github/h5/hexo/index.html",
    redirect: "/github/h5/hexo/"
  },
  {
    name: "v-306b5861",
    path: "/github/h5/jekyll/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-306b5861").then(next)
    },
  },
  {
    path: "/github/h5/jekyll/index.html",
    redirect: "/github/h5/jekyll/"
  },
  {
    name: "v-160171b2",
    path: "/github/ios/all/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-160171b2").then(next)
    },
  },
  {
    path: "/github/ios/all/index.html",
    redirect: "/github/ios/all/"
  },
  {
    name: "v-560f20a7",
    path: "/github/ios/project/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-560f20a7").then(next)
    },
  },
  {
    path: "/github/ios/project/index.html",
    redirect: "/github/ios/project/"
  },
  {
    name: "v-eab50402",
    path: "/github/ios/synthesize/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-eab50402").then(next)
    },
  },
  {
    path: "/github/ios/synthesize/index.html",
    redirect: "/github/ios/synthesize/"
  },
  {
    name: "v-5d699df2",
    path: "/github/vue/all/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5d699df2").then(next)
    },
  },
  {
    path: "/github/vue/all/index.html",
    redirect: "/github/vue/all/"
  },
  {
    name: "v-0c34d607",
    path: "/github/vue/project/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0c34d607").then(next)
    },
  },
  {
    path: "/github/vue/project/index.html",
    redirect: "/github/vue/project/"
  },
  {
    name: "v-25019561",
    path: "/join/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Join", "v-25019561").then(next)
    },
  },
  {
    path: "/join/index.html",
    redirect: "/join/"
  },
  {
    name: "v-c71dcc8a",
    path: "/message/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c71dcc8a").then(next)
    },
  },
  {
    path: "/message/index.html",
    redirect: "/message/"
  },
  {
    name: "v-87d83dbe",
    path: "/search/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-87d83dbe").then(next)
    },
  },
  {
    path: "/search/index.html",
    redirect: "/search/"
  },
  {
    name: "v-d85dfcd8",
    path: "/tool/all/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d85dfcd8").then(next)
    },
  },
  {
    path: "/tool/all/index.html",
    redirect: "/tool/all/"
  },
  {
    name: "v-b604cc8c",
    path: "/tool/synthesize/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b604cc8c").then(next)
    },
  },
  {
    path: "/tool/synthesize/index.html",
    redirect: "/tool/synthesize/"
  },
  {
    name: "v-28248de5",
    path: "/github/h5/php/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-28248de5").then(next)
    },
  },
  {
    path: "/github/h5/php/index.html",
    redirect: "/github/h5/php/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]