/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "资源库",
  "description": "",
  "base": "/",
  "pages": [
    {
      "frontmatter": {
        "layout": "HomeLayout"
      },
      "regularPath": "/",
      "key": "v-6dd8c284",
      "path": "/"
    },
    {
      "title": "全部",
      "frontmatter": {},
      "regularPath": "/game/all/",
      "key": "v-2b910858",
      "path": "/game/all/"
    },
    {
      "title": "棋牌",
      "frontmatter": {},
      "regularPath": "/game/chesscard/",
      "key": "v-f094d918",
      "path": "/game/chesscard/"
    },
    {
      "title": "冒险",
      "frontmatter": {},
      "regularPath": "/game/risk/",
      "key": "v-16017424",
      "path": "/game/risk/"
    },
    {
      "title": "射击",
      "frontmatter": {},
      "regularPath": "/game/shoot/",
      "key": "v-15069ed8",
      "path": "/game/shoot/"
    },
    {
      "title": "益智",
      "frontmatter": {},
      "regularPath": "/game/smart/",
      "key": "v-8f482b58",
      "path": "/game/smart/"
    },
    {
      "title": "综合",
      "frontmatter": {},
      "regularPath": "/game/synthesize/",
      "key": "v-81c7d824",
      "path": "/game/synthesize/"
    },
    {
      "title": "全部",
      "frontmatter": {},
      "regularPath": "/github/android/all/",
      "key": "v-81780c32",
      "path": "/github/android/all/"
    },
    {
      "title": "动画",
      "frontmatter": {},
      "regularPath": "/github/android/animation/",
      "key": "v-c5bfcbf2",
      "path": "/github/android/animation/"
    },
    {
      "title": "架构",
      "frontmatter": {},
      "regularPath": "/github/android/architecture/",
      "key": "v-69247671",
      "path": "/github/android/architecture/"
    },
    {
      "title": "组件",
      "frontmatter": {},
      "regularPath": "/github/android/component/",
      "key": "v-ac727eb2",
      "path": "/github/android/component/"
    },
    {
      "title": "完整项目",
      "frontmatter": {},
      "regularPath": "/github/android/project/",
      "key": "v-2ab17667",
      "path": "/github/android/project/"
    },
    {
      "title": "综合",
      "frontmatter": {},
      "regularPath": "/github/android/synthesize/",
      "key": "v-4f7fc17a",
      "path": "/github/android/synthesize/"
    },
    {
      "title": "自定义View",
      "frontmatter": {},
      "regularPath": "/github/android/view/",
      "key": "v-1aa30e66",
      "path": "/github/android/view/"
    },
    {
      "title": "全部",
      "frontmatter": {},
      "regularPath": "/github/flutter/all/",
      "key": "v-72675a72",
      "path": "/github/flutter/all/"
    },
    {
      "title": "完整项目",
      "frontmatter": {},
      "regularPath": "/github/flutter/project/",
      "key": "v-37aaa0c7",
      "path": "/github/flutter/project/"
    },
    {
      "title": "H5",
      "frontmatter": {},
      "regularPath": "/github/h5/h5/",
      "key": "v-33e83461",
      "path": "/github/h5/h5/"
    },
    {
      "title": "全部",
      "frontmatter": {},
      "regularPath": "/github/h5/all/",
      "key": "v-2c855a5a",
      "path": "/github/h5/all/"
    },
    {
      "title": "Hexo",
      "frontmatter": {},
      "regularPath": "/github/h5/hexo/",
      "key": "v-ed11587e",
      "path": "/github/h5/hexo/"
    },
    {
      "title": "Jekyll",
      "frontmatter": {},
      "regularPath": "/github/h5/jekyll/",
      "key": "v-306b5861",
      "path": "/github/h5/jekyll/"
    },
    {
      "title": "全部",
      "frontmatter": {},
      "regularPath": "/github/ios/all/",
      "key": "v-160171b2",
      "path": "/github/ios/all/"
    },
    {
      "title": "完整项目",
      "frontmatter": {},
      "regularPath": "/github/ios/project/",
      "key": "v-560f20a7",
      "path": "/github/ios/project/"
    },
    {
      "title": "综合",
      "frontmatter": {},
      "regularPath": "/github/ios/synthesize/",
      "key": "v-eab50402",
      "path": "/github/ios/synthesize/"
    },
    {
      "title": "全部",
      "frontmatter": {},
      "regularPath": "/github/vue/all/",
      "key": "v-5d699df2",
      "path": "/github/vue/all/"
    },
    {
      "title": "完整项目",
      "frontmatter": {},
      "regularPath": "/github/vue/project/",
      "key": "v-0c34d607",
      "path": "/github/vue/project/"
    },
    {
      "frontmatter": {
        "layout": "Join"
      },
      "regularPath": "/join/",
      "key": "v-25019561",
      "path": "/join/"
    },
    {
      "frontmatter": {
        "comments": true
      },
      "regularPath": "/message/",
      "key": "v-c71dcc8a",
      "path": "/message/"
    },
    {
      "frontmatter": {},
      "regularPath": "/search/",
      "key": "v-87d83dbe",
      "path": "/search/"
    },
    {
      "title": "全部",
      "frontmatter": {},
      "regularPath": "/tool/all/",
      "key": "v-d85dfcd8",
      "path": "/tool/all/"
    },
    {
      "title": "综合",
      "frontmatter": {},
      "regularPath": "/tool/synthesize/",
      "key": "v-b604cc8c",
      "path": "/tool/synthesize/"
    },
    {
      "title": "PHP",
      "frontmatter": {},
      "regularPath": "/github/h5/php/",
      "key": "v-28248de5",
      "path": "/github/h5/php/"
    }
  ],
  "themeConfig": {
    "search": true,
    "nav": [
      {
        "text": "主页",
        "link": "/"
      },
      {
        "text": "Github资源",
        "items": [
          {
            "text": "Android",
            "link": "/github/android/all/"
          },
          {
            "text": "IOS",
            "link": "/github/ios/all/"
          },
          {
            "text": "Flutter",
            "link": "/github/flutter/all/"
          },
          {
            "text": "Vue",
            "link": "/github/vue/all/"
          },
          {
            "text": "H5",
            "link": "/github/h5/all/"
          }
        ]
      },
      {
        "text": "游戏",
        "link": "/game/all/"
      },
      {
        "text": "工具",
        "link": "/tool/all/"
      },
      {
        "text": "留言",
        "link": "/message/"
      },
      {
        "text": "Gitter聊天",
        "link": "https://gitter.im/leachchen/fullstack?utm_source=share-link&utm_medium=link&utm_campaign=share-link"
      },
      {
        "text": "博客",
        "link": "https://www.leachchen.com/blog"
      },
      {
        "text": "加入",
        "link": "/join/"
      }
    ],
    "sidebar": {
      "/github/android/": [
        {
          "title": "Android Github",
          "collapsable": false,
          "children": [
            "all/",
            "project/",
            "animation/",
            "view/",
            "synthesize/",
            "component/",
            "architecture/"
          ]
        }
      ],
      "/github/ios/": [
        {
          "title": "IOS Github",
          "collapsable": false,
          "children": [
            "all/",
            "project/",
            "synthesize/"
          ]
        }
      ],
      "/github/flutter/": [
        {
          "title": "Flutter Github",
          "collapsable": false,
          "children": [
            "all/",
            "project/"
          ]
        }
      ],
      "/github/vue/": [
        {
          "title": "Vue Github",
          "collapsable": false,
          "children": [
            "all/",
            "project/"
          ]
        }
      ],
      "/github/h5/": [
        {
          "title": "H5 Github",
          "collapsable": false,
          "children": [
            "all/",
            "h5/",
            "hexo/",
            "jekyll/",
            "php/"
          ]
        }
      ],
      "/game/": [
        {
          "title": "Games",
          "collapsable": false,
          "children": [
            "all/",
            "smart/",
            "chesscard/",
            "shoot/",
            "risk/",
            "synthesize/"
          ]
        }
      ],
      "/tool/": [
        {
          "title": "Tools",
          "collapsable": false,
          "children": [
            "all/",
            "synthesize/"
          ]
        }
      ]
    }
  }
}